// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Org          string
	Policy       string
	Role         string
	RolePolicies string
	User         string
	UserRoles    string
	Zone         string
}{
	Org:          "org",
	Policy:       "policy",
	Role:         "role",
	RolePolicies: "role_policies",
	User:         "user",
	UserRoles:    "user_roles",
	Zone:         "zone",
}
