// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Conditions", testConditionsUpsert)

	t.Run("Orgs", testOrgsUpsert)

	t.Run("Policies", testPoliciesUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("Zones", testZonesUpsert)
}
